### PR TITLE
Attempt to write correct arbitrary instances for fixed-length values

### PR DESCRIPTION
**Pull request by AriFordsham**
Shrink has been omitted because shrinking doesn't make sense on fixed-length values.

I am not sure all the hash algorithms are correct as I'm getting mixed messages from various sources. I would appreciate a review from someone who knows what they're talking about.

### CODE REVIEW

**Comment by kozross** [comment]
Are all `BuiltinByteString`s capped at 64 bytes?

**Comment by AriFordsham** [comment]
I don't know.

**Comment by kozross** [comment]
The reason I ask is because I wasn't aware that was a limitation. I know some things do have internal invariants (which was the subject of #165, for instance), but I don't think it's a hard cap in general.

**Comment by AriFordsham** [comment]
Datatypes such as hashes are fixed-length by nature. TokenName is limited to 32 bytes.

**Comment by kozross** [comment]
Ah, yes, my bad, was misreading. Clearly having a strange day today...

**Review by kozross — CHANGES_REQUESTED** [review]
Could you retarget this to `master` please?

**Review by kozross — APPROVED** [review]

**Pull request merged**
