### PR TITLE
Add `Natural` functions for `AssocMap`

### LINKED ISSUE #163: `Natural` functions for Map
We have a series of helper functions for Lists that work with Naturals over Ints, could we get this for Maps?
The pattern of functions like `Map.take . fromInteger . natToInteger` gets a little cumbersome

### PR DESCRIPTION
**Pull request by re-xyr**
Fixes #163. `Witherable` functions not added for now - needs further discussion.

### CODE REVIEW

**Review by kozross — APPROVED** [review]

**Review by kozross — APPROVED** [review]

**Comment by kozross** [comment]
@samuelWilliams99 - good by you?

**Review by samuelWilliams99 — APPROVED** [review]
Nothing major, just some notes

**Comment by kozross** [comment]
@samuelWilliams99 `fitsOnChain` is generally meant to be a first pass; it spits out the size you have, and then you use `fitsUnder` or `fitsInto` to set a more precise measure.

**Comment by re-xyr** [comment]
@kozross Do you think we need to introduce any `fitsUnder` tests for now?

**Comment by samuelWilliams99** [comment]
Since it spits out the size, im guessing any obviously large sizes would be noticed, if @re-xyr can confirm this, I'm happy to merge at least :)

**Comment by kozross** [comment]
@re-xyr We certainly _should_, but for now, I'll merge it, and open a separate issue.

**Pull request merged**
