### PR TITLE
Update `hie.yaml`

### PR DESCRIPTION
**Pull request by re-xyr**
In addition to that, Cabal library names are not... "scoped"? So there will be trouble in HLS when two test modules are both `property` or `laws`. Therefore I added prefixes to all test modules.

### CODE REVIEW

**Comment by jeffhappily** [comment]
@re-xyr You should be able to prepend the package name in front of the component as shown in the example in `implicit-hie` https://github.com/Avi-D-coder/implicit-hie#readme to disambiguate them

**Comment by re-xyr** [comment]
@jeffhappily Thanks, I didn't know that! The `implicit-hie` tool looks nice - maybe I should use it to generate hie files instead.

**Comment by kozross** [comment]
@re-xyr @jeffhappily - are you both happy with this? I want to merge, but I can't evaluate it.

**Comment by re-xyr** [comment]
@kozross This PR is outdated for now - I will update it with the `hie.yaml` that `implicit-hie` generates next week, or @jeffhappily could do that if they'd like to.

**Comment by jeffhappily** [comment]
Sure, I can help work on this

**Comment by jeffhappily** [comment]
I'm not sure why I'm having permission issue when I try to push to the repo, let me try to debug

```
ERROR: Permission to Liqwid-Labs/plutus-extra.git denied to jeffhappily.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by jeffhappily** [comment]
I've created another PR to update this branch (PR) with the new changes and merging with the latest master https://github.com/Liqwid-Labs/plutus-extra/pull/144

**Comment by kozross** [comment]
I'll just give you permissions, it's easier.

**Comment by jeffhappily** [comment]
@kozross I've updated the PR, it's good to go except the CI is failing for some strange reason

**Review by kozross — APPROVED** [review]

**Pull request merged**
