### PR TITLE
Complete the laws in `plutusOrdLaws`

### LINKED ISSUE #68: Checks for agreement between Plutus Eq and Plutus Ord
We want to ensure that they're not giving inconsistent answers. So, something like:

* If `x == y`, then `compare x y == EQ`; and
* If `x /= y`, then `compare x y /= EQ`.

### PR DESCRIPTION
**Pull request by re-xyr**
Fixes #68

### CODE REVIEW

**Review by kozross — CHANGES_REQUESTED** [review]
We also need a separate

**Comment by re-xyr** [comment]
I set 33.3% coverage for preconditions `x < y` or `x > y` (it turned out to be ~47% in `plutus-numeric`), and 50.0% coverage for preconditions `x >= y` or `x <= y`. Not sure if this is reasonable?

**Comment by re-xyr** [comment]
I actually don't understand why 47% coverage would fail, given the docs for `checkCoverage` says

> For statistical reasons, `checkCoverage` will not reject coverage levels that are only slightly below the required levels. If the required level is `p` then an actual level of `tolerance * p` will be accepted. The default value is `0.9`.

And I think that means anything above 45% should be accepted as 50% coverage?

**Comment by kozross** [comment]
@re-xyr I'll investigate this - it definitely seems a little bit suspect. Feel free to move onto other things in the meantime.

**Comment by sergesku** [comment]
> I actually don't understand why 47% coverage would fail, given the docs for `checkCoverage` says
> 
> > For statistical reasons, `checkCoverage` will not reject coverage levels that are only slightly below the required levels. If the required level is `p` then an actual level of `tolerance * p` will be accepted. The default value is `0.9`.
> 
> And I think that means anything above 45% should be accepted as 50% coverage?

The reason is that the `tolerance * p` is used not to compare with the real coverage, but to check the Binomial proportion confidence interval (please do not ask about this).
https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Wilson_score_interval

**Review by kozross — APPROVED** [review]

**Pull request merged**
